- name: Add MariaDB repo
  template:
    src: mariadb.repo.j2
    dest: /etc/yum.repos.d/mariadb.repo
    force: true

- name: Install packages
  package:
    name: "{{ item }}"
    state: installed
    enablerepo: mariadb
  with_items: "{{ mariadb_packages }}"
  tags: mariadb
  when: rhel_version == 7

- name: Install packages step 1
  dnf:
    name: boost-program-options
    state: installed
  tags: mariadb
  when: rhel_version == 8

- name: Install packages step 2
  dnf:
    name: [MariaDB-server, MariaDB-client]
    state: installed
    disablerepo: AppStream
  tags: mariadb
  when: rhel_version == 8
