# roles/mariadb/tasks/main.yml
---
- name: check if package is installed
  package:
    name: mysql
    state: present
  check_mode: true
  register: mariadb_check

- include: install.yml
  when: mariadb_check.changed
