# Shared
before_script:
  - source ci/bin/prepare_envs

variables:
  BUILDS_FOLDER: builds
  LOCAL_BUILD_PATH: "${BUILDS_FOLDER}/${CI_COMMIT_SHORT_SHA}"
  REMOTE_BUILD_PATH: "${BUILDS_FOLDER}/${CI_COMMIT_SHORT_SHA}"

# Stages
stages:
  - build
  - quality_checks
  - release

# Build jobs
build_scripts:
  tags: [shell]
  stage: build
  interruptible: true
  script:
    - ci/bin/build/compile
    - ci/bin/testing/validate_scripts
  artifacts:
    expire_in: 1 hour
    paths:
      - scripts/install.sh
      - scripts/add-site.sh
      - scripts/enable-ssl.sh
      - scripts/fix-renewal-certs-cron-job.sh
      - scripts/test-run-command.sh
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: never
    - if: '$CI_COMMIT_REF_NAME =~ /(release-|current)/'
      when: never
    - if: '$CI_COMMIT_REF_NAME == "INST-126"/'
      when: manual
    - when: never

# Quality checks
.quality-checks-common:
  stage: quality_checks
  interruptible: true
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: never
    - if: '$CI_COMMIT_REF_NAME =~ /(release-|current)/'
      when: never
    - if: '$CI_COMMIT_REF_NAME == "INST-126"/'
      when: manual
    - when: never

run_rspec:
  extends: [.quality-checks-common]
  tags: [shell]
  script:
    - ci/bin/testing/validate_scripts
    - ci/bin/testing/install_bundle
    - ci/bin/testing/run_rspec
  cache:
    key: vendor
    paths:
      - scripts/vendor/
  dependencies:
    - build_scripts


# Deployment jobs
.deployment-jobs-common:
  stage: deployment


legacy_deploy:
  extends: [.deployment-jobs-common]
  tags: [shell]
  script:
    - ci/bin/deployment/allow_git_push
    - ci/bin/deployment/legacy_deploy
  when: manual
  allow_failure: false
  dependencies:
    - build_scripts
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: never
    - if: '$CI_COMMIT_REF_NAME =~ /(master)/'
      when: on_success
    - if: '$CI_COMMIT_REF_NAME == "INST-126"/'
      when: manual
    - when: never


deploy:
  extends: [.deployment-jobs-common]
  tags: [kubernetes]
  image: apliteni/mc
  script:
    - ci/bin/deployment/create_build
    - ci/bin/deployment/prepare_mc
    - ci/bin/deployment/upload_to_s3
  allow_failure: false
  dependencies:
    - build_scripts
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: never
    - if: '$CI_COMMIT_REF_NAME =~ /(master)/'
      when: on_success
    - if: '$CI_COMMIT_REF_NAME == "INST-126"/'
      when: always
    - if: '$ACTION == "build"/'
      when: always
    - when: never
