# Shared
before_script:
  - source ci/bin/prepare_envs
  - ci/bin/allow_git_push

# Stages
stages:
  - build
  - quality_checks
  - release

# Jobs
build_scripts:
  tags: [shell]
  stage: build
  script:
    - ci/bin/build/compile
    - ci/bin/testing/validate_scripts
  artifacts:
    expire_in: 1 hour
    paths:
      - scripts/install.sh
      - scripts/add-site.sh
      - scripts/enable-ssl.sh
      - scripts/fix-renewal-certs-cron-job.sh
      - scripts/test-run-command.sh
  except:
    - /^release-/
    - /^current$/

run_rspec:
  tags: [kubernetes]
  stage: quality_checks
  dependencies:
    - build_scripts
  script:
    - ci/bin/testing/validate_scripts
    - ci/bin/testing/install_bundle
    - ci/bin/testing/run_rspec
  cache:
    key: vendor
    paths:
      - vendor/
  except:
    - /^release-/
    - /^current$/

deploy:
  tags: [shell]
  stage: release
  script: ci/bin/deploy.sh
  when: manual
  allow_failure: false
  only:
    - /^master$/
  except:
    - /^release-/
    - /^current$/
