# Shared
before_script:
  - source ci/bin/prepare_envs

# Stages
stages:
  - build
  - quality_checks
  - release

# Jobs
build_scripts:
  tags: [shell]
  stage: build
  interruptible: true
  script:
    - ci/bin/build/compile
    - ci/bin/testing/validate_scripts
  artifacts:
    expire_in: 1 hour
    paths:
      - scripts/install.sh
      - scripts/add-site.sh
      - scripts/enable-ssl.sh
      - scripts/fix-renewal-certs-cron-job.sh
      - scripts/test-run-command.sh
  except:
    - /^release-/
    - /^current$/

run_rspec:
  stage: quality_checks
  tags: [kubernetes]
  interruptible: true
  image: apliteni/bundle-rspec
  dependencies:
    - build_scripts
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375
  script:
    - ci/bin/testing/validate_scripts
    - ci/bin/testing/install_bundle
    - ci/bin/testing/run_rspec
  cache:
    key: vendor
    paths:
      - scripts/vendor/
  except:
    - /^release-/
    - /^current$/

deploy:
  tags: [shell]
  stage: release
  script:
    - ci/bin/allow_git_push
    - ci/bin/deploy.sh
  when: manual
  allow_failure: false
  only:
    - /^master$/
  except:
    - /^release-/
    - /^current$/
