- name: Remove old files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/nginx/ssl/cert.pem
    - /etc/nginx/ssl/privkey.pem
    - /etc/ssl/certs/dhparam.pem
    - /root/hosts.txt
    - "{{ keitaro_root }}/install.php"
    - /etc/logrotate.d/mariadb
    - /etc/keitaro/roadrunner.yml
    - /etc/sudoers.d/10-enable-ssl-command

- name: Remove all cron tasks of nginx user
  shell: "crontab -r -u {{ nginx_user }} || true"

- name: Remove old root cron.php task
  shell: 'sed -i /cron.php/d /var/spool/cron/root'
