- name: set variable
  shell: mysql --version
  register: mysql_version_output
- set_fact:
    mariadb_version_output: "{{ mysql_version_output.stdout | regex_search('(?<=Distrib )(.*)(?=-MariaDB)') }}"
    
- name: Add MariaDB repo
  template:
    src: mariadb.repo.j2
    dest: /etc/yum.repos.d/mariadb.repo
  force: yes  
    
- name: Ensure service is stopped
  service:
    name: mariadb
    state: stopped
  when: mariadb_version_output is not search('10.4') 
    
- name: remove old maria Centos 7
  package:
    name: "{{ item }}"
    state: absent
  with_items: "{{ mariadb_packages }}"
  tags: mariadb
  when: rhel_version == 7 and mariadb_version_output is not search('10.4')

- name: remove old galera
  package:
    name: galera
    state: absent
  tags: mariadb
  when: mariadb_version_output is not search('10.4')

- name: remove old maria Centos 8
  dnf:
    name: [MariaDB-server, MariaDB-client]
    state: absent
  tags: mariadb
  when: rhel_version == 8 and mariadb_version_output is not search('10.4')

- name: Install packages
  package:
    name: "{{ item }}"
    state: installed
    enablerepo: mariadb
  with_items: "{{ mariadb_packages }}"
  tags: mariadb
  when: rhel_version == 7

- name: Install packages step 1
  dnf:
    name: boost-program-options
    state: installed
  tags: mariadb
  when: rhel_version == 8

- name: Install packages step 2
  dnf:
    name: [MariaDB-server, MariaDB-client]
    state: installed
    disablerepo: AppStream
  tags: mariadb
  when: rhel_version == 8

- name: Make sure pymysql is present
  become: true # needed if the other tasks are not played as root
  pip:
    name: pymysql
    state: present
  tags: mariadb
  when: rhel_version == 8
  
- name: Update root password
  mysql_user:
    login_unix_socket: "{{ mariadb_socket }}"
  with_items:
    - 127.0.0.1
    - ::1
    - localhost
  tags: mariadb
  when: rhel_version == 8
  

