- name: Create the directory, if it doesnt exist already
  file:
    path: /var/log/journal
    state: directory

- name:
  shell: |
    systemd-tmpfiles --create --prefix /var/log/journal
    systemctl restart systemd-journald
    
- name: Ensure systemd-journald is started
  service:
    name: systemd-journald
    state: started
    enabled: yes
