- name: Install certbot
  package:
    name: certbot
    state: installed
  when: rhel_version == 7
  
- name: remove the old Certbot
  dnf:
    name: installed
    state: absent  
  when: rhel_version == 8
  
- name: remove old files
  file:
    path: "{{ certbot_dir }}"
    state: absent

- name: Creates certbot-auto directory
  file:
    path: "{{ certbot_dir }}"
    state: directory  
  
- name: download certbot-auto
  get_url:
    url: "{{ certbot_url }}"
    dest: "{{ certbot_dir }}/certbot-auto"
    mode: '0755'
    owner: "root"
    force: yes
  when: rhel_version == 8
  
- name: install certbot-auto
  shell: cd {{ certbot_dir }} && ./certbot-auto --install-only --non-interactive
  
- name: Set Certbot script variable.
  set_fact:
    certbot_script: "{{ certbot_dir }}/certbot-auto"

- name: Ensure certbot-auto is executable.
  file:
    path: "{{ certbot_script }}"
    mode: 0755

- name: Create directory for ssl certs
  file:
    path: "{{ ssl_root }}"
    state: directory

- name: Remove old renewal certs job
  cron:
    name: Renew Let's Encrypt certs
    state: absent
    user: "{{ nginx_user }}"
