- name: create temporary build directory
  tempfile:
    state: directory
    suffix: build
  register: openssl_tmp_dir  

- name: Unarchive a file that needs to be downloaded (added in 2.0)
  unarchive:
    src: https://ftp.openssl.org/source/old/1.1.1/openssl-1.1.1.tar.gz
    dest: "{{ openssl_tmp_dir.path }}"
    remote_src: yes

- name: Run make install
  make:
    chdir: "{{ openssl_tmp_dir.path }}"
    target: install
    
- name: Exports
  shell: |
    export LD_LIBRARY_PATH=/usr/local/lib:/usr/local/lib64
    echo "export LD_LIBRARY_PATH=/usr/local/lib:/usr/local/lib64" >> ~/.bashrc

- name: use the registered var and the file module to remove the temporary file
  file:
    path: "{{ openssl_tmp_dir.path }}"
    state: absent
