- name: Create directory for ssl certs
  file:
    path: "{{ openssl_dir}}"
    state: directory

- name: Unarchive a file that needs to be downloaded (added in 2.0)
  unarchive:
    src: https://ftp.openssl.org/source/old/1.1.1/openssl-1.1.1.tar.gz
    dest: "{{ openssl_dir }}"
    remote_src: yes

- name: Install openssl
  command: "{{ item }}"
  with_items:
    - cd {{ openssl_dir }}
    - ./config --prefix=/usr --openssldir=/etc/ssl --libdir=lib no-shared zlib-dynamic
    - make
    - make test
    - make install
    - echo "export LD_LIBRARY_PATH=/usr/local/lib:/usr/local/lib64" >> ~/.bashrc

- name: use the registered var and the file module to remove the temporary file
  file:
    path: "{{ openssl_dir }}"
    state: absent
