- name: Unarchive a file that needs to be downloaded (added in 2.0)
  unarchive:
    src: https://ftp.openssl.org/source/old/1.1.1/openssl-1.1.1.tar.gz
    dest: /usr/local/bin/
    remote_src: yes
    list_files: yes
  register: archive_contents

- name: Install openssl
  command: "{{ item }}"
  with_items:
    - cd {{ archive_contents.files[0] }} | \
    - ./config --prefix=/usr --openssldir=/etc/ssl --libdir=lib no-shared zlib-dynamic | \
    - make | \
    - make test | \
    - make install | \
    - export LD_LIBRARY_PATH=/usr/local/lib:/usr/local/lib64 | \
    - echo "export LD_LIBRARY_PATH=/usr/local/lib:/usr/local/lib64" >> ~/.bashrc
