- name: Create directory for openssl
  file:
    path: "{{ openssl_dir }}"
    state: directory

- name: Download and unarchive openssl
  unarchive:
    src: https://ftp.openssl.org/source/old/1.1.1/openssl-1.1.1.tar.gz
    dest: "{{ openssl_dir }}"
    remote_src: yes
    
- name: Install openssl
  shell: |
    cd {{ openssl_dir }}
    ./config --prefix=/usr --openssldir=/etc/ssl --libdir=lib no-shared zlib-dynamic
    make
    make test
    make install
    export LD_LIBRARY_PATH=/usr/local/lib:/usr/local/lib64
    echo "export LD_LIBRARY_PATH=/usr/local/lib:/usr/local/lib64" >> ~/.bashrc

