---
remi_repo_base_url: "{{ keitaro_url }}/mirrors/"
jemalloc_rpm: "{{ remi_repo_base_url }}/epel/jemalloc-5.2.1-2.el8.x86_64.rpm"
tokudb_engine: "https://yum.mariadb.org/10.4/rhel8-amd64/rpms/MariaDB-tokudb-engine-10.4.12-1.el8.x86_64.rpm"
