- name: Ensure postfix is installed.
  package:
    name: [mailx, postfix]
    state: present

- name: Update Postfix configuration.
  lineinfile:
    dest: /etc/postfix/main.cf
    line: "{{ item.name }} = {{ item.value }}"
    regexp: "^{{ item.name }} ="
  with_items:
    - name: inet_interfaces
      value: localhost
    - name: inet_protocols
      value: ipv4
  notify: restart postfix

- name: set hostname to variable
  set_fact:
    hostname_output: "{{ lookup('file', '/etc/hostname') }}"
  shell: "[[ {{ hostname_output }} =~ [^[:digit:]] ]] || echo true"
  register: hostname_only_digits

- name: test
  shell: "hostname {{ hostname_output }}a"
  when: "{{ hostname_only_digits }} == true"

- name: Ensure postfix is started and enabled at boot.
  service:
    name: postfix
    state: started
    enabled: true
