# roles/mariadb/vars/main.yml
---

mariadb_packages:
  - MariaDB
  - MariaDB-server
  - MySQL-python

mariadb_service: mariadb

mariadb_config: /etc/my.cnf.d/network.cnf
mariadb_my_config: ~/.my.cnf

mariadb_version: 10.4
tokudb_engine: "https://yum.mariadb.org/{{ mariadb_version }}/rhel8-amd64/rpms/MariaDB-tokudb-engine-{{ mariadb_version_output }}-1.el8.x86_64.rpm"


