# roles/mariadb/vars/main.yml
---

mariadb_packages:
  - MariaDB
  - MariaDB-server
  - MySQL-python

mariadb_service: mariadb

mariadb_version: 10.4
tokudb_engine: "https://yum.mariadb.org/{{ mariadb_version }}/rhel8-amd64/rpms/MariaDB-tokudb-engine-{{ tokudb_version }}-1.el8.x86_64.rpm"


