- uri:
    url: https://api.github.com/repos/ansible/ansible/releases/latest
    return_content: true
  register: json_reponse
  
- name: Register last roadrunner version
  set_fact:
    tag_name: "{{ json_reponse.json.tag_name }}"

- name: Download and unpack RoadRunner
  shell: >
    curl -fskSL {{ json_reponse.json.tarball_url }} | \
     tar -xz --no-same-owner --no-same-permissions --strip 1 {{ rr_release_name }}/rr && \
     mv /usr/local/bin/rr /usr/local/bin/roadrunner-{{ rr_version }}
  args:
    chdir: /usr/local/bin
    creates: "/usr/local/bin/roadrunner-{{ rr_version }}"

- name: Make symlink to current roadrunner
  file:
    src: "roadrunner-{{ rr_version }}"
    dest: /usr/local/bin/roadrunner
    state: link
    force: true

- name: Make rr -> roadrunner symlink
  file:
    src: "roadrunner"
    dest: /usr/local/bin/rr
    state: link
    force: true
