- name: Configure cron to run keitaro task every minute channel 1
  cron:
    user: "{{ keitaro_user }}"
    name: "keitaro cron channel 1"
    job: "{{ php_path }} {{ keitaro_root }}/cron.php --channel=1"

- name: Configure cron to run keitaro task every minute channel 2
  cron:
    user: "{{ keitaro_user }}"
    name: "keitaro cron channel 2"
    job: "{{ php_path }} {{ keitaro_root }}/cron.php --channel=2"

- name: Configure cron to run keitaro task every minute channel 3
  cron:
    user: "{{ keitaro_user }}"
    name: "keitaro cron channel 3"
    job: "{{ php_path }} {{ keitaro_root }}/cron.php --channel=3"

- name: Configure cron to run keitaro task every minute channel 4
  cron:
    user: "{{ keitaro_user }}"
    name: "keitaro cron channel 4"
    job: "{{ php_path }} {{ keitaro_root }}/cron.php --channel=4"

- name: Configure cron to update geo databases every week
  cron:
    user: "{{ keitaro_user }}"
    name: "update geodbs"
    weekday: "{{ 6 | random }}"
    hour: "{{ 23 | random }}"
    minute: "{{ 59 | random }}"
    job: "{{ php_path }} {{ keitaro_root }}/bin/cli.php geodbs:update_all"

- name: Generate watch list if it isn't exist.
  copy:
    dest: "{{ keitaro_watch_list }}"
    content: >
      application/redirects/
      application/macros/
      application/filters/
      application/config/config.ini.php
    force: no
