- name: Configure cron to run keitaro task every minute
  cron:
    user: "{{ keitaro_user }}"
    name: "keitaro"
    job: "{{ php_path }} {{ keitaro_root }}/cron.php"

- name: Configure cron to update geo databases every week
  cron:
    user: "{{ keitaro_user }}"
    name: "update geodbs"
    weekday: "{{ 6 | random }}"
    hour: "{{ 23 | random }}"
    minute: "{{ 59 | random }}"
    job: "{{ php_path }} {{ keitaro_root }}/bin/cli.php geodbs:update_all"

- name: Configure cron to clear old namespaced cache every week
  cron:
    user: "{{ keitaro_user }}"
    name: "flush old cache"
    weekday: "{{ 6 | random }}"
    hour: "{{ 22 | random }}"
    minute: "{{ 59 | random }}"
    job: "{{ php_path }} {{ keitaro_root }}/bin/cli.php system:flush_old_cache"

- name: Generate watch list if it isn't exist.
  copy:
    dest: "{{ keitaro_watch_list }}"
    content: >
      application/redirects/
      application/macros/
      application/filters/
      application/config/config.ini.php
    force: no
