- name: Create backup dir
  file:
    path: "{{ keitaro_backup_dir }}"
    mode: 0700
    state: directory
    
- set_fact:
    backups_count: "cd /root/test && ls | wc -l"

- name: get older backups
  shell: "find /root/test -maxdepth 1 -printf '- %p\n' | sort | tail -n+7"
  register: directories_list
  when: backups_count > 5
  
- debug:
    var: directories_list.stdout_lines

- name: remove older backups
  file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ directories_list.stdout_lines }}" 

- name: Backup configs
  shell: cp -R /etc/{{ item }} "/root/test/{{ item }}"
  with_items:
    - letsencrypt
    - logrotate.d
    - my.cnf.d
    - nginx
    - php
    - selinux
