- name: Create backup dir
  file:
    path: "{{ keitaro_backup_dir }}"
    mode: 0700
    state: directory

- name: Creates letsencrypt directory if not exist
  file:
    path: /etc/letsencrypt
    state: directory

- name: Backup configs
  shell: cp -R /etc/{{ item }} "{{ keitaro_backup_dir }}/{{ item }}"
  with_items:
    - letsencrypt
    - logrotate.d
    - my.cnf.d
    - nginx
    - php
    - selinux

- set_fact:
    backups_count: "cd {{ keitaro_backups }} && ls | wc -l"

- name: get older backups
  shell: "find {{ keitaro_backups }} -maxdepth 1 -type d -printf '%p\n' | sort | head -1"
  register: directories_list
  when: backups_count > 5

- name: remove older backups
  file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ directories_list.stdout_lines }}"
  when: backups_count > 5
