- name: Create backup dir
  file:
    path: "{{ keitaro_backup_dir }}"
    mode: 0700
    state: directory

- name: Backup configs
  shell: test -e /etc/{{item}} && cp -R /etc/{{ item }} {{ keitaro_backup_dir }}/{{ item }}
  with_items:
    - letsencrypt
    - logrotate.d
    - my.cnf.d
    - nginx
    - php
    - selinux

- name: Get older backups list
  shell: "ls {{ keitaro_backups }} | head -n -{{ keitaro_backups_amount }}"
  register: list_backup_directories_result

- name: Remove older backups
  file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ list_backup_directories_result.stdout_lines }}"
