- name: remove old maria Centos 7
  package:
    name: "{{ item }}"
    state: absent
  with_items: "{{ mariadb_packages }}"
  tags: mariadb

- name: remove old galera
  package:
    name: galera
    state: absent
  tags: mariadb

- name: remove old maria Centos 8
  dnf:
    name: [MariaDB-server, MariaDB-client]
    state: absent
  tags: mariadb
