- name: Install jemalloc rpm for Centos 8
  yum:
    name: "{{ jemalloc_rpm }}"
    state: installed

- name:
  yum:
    name: jemalloc
    state: installed

- name: Install TokuDB Engine Centos 8
  yum:
    name: "{{ tokudb_engine }}"
    state: installed

- name: Restart MariaDB service
  service:
    name: mariadb
    state: restarted
